# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 505b5ea081b43466eb411b7243e7591c499ea4184ecf4d64ac40a4dc20c1cce6f67679341270648e2eda620b3043d5f517982cb0ba04835c4cbf7ecb4e62c244

test:
  secret_key_base: bae1a848e1ab261582df5783094f1bbb44fd109b8b03f919f43985face29a14ace1d07a684dee7a0fbb6e3c5908902f7391bd00e4e3caca240ef75e826117ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
